name: liquid_ai
description: "A Flutter package for Liquid AI integrations with LEAP SDK."
version: 0.0.1
homepage: https://github.com/danielsogl/liquid_ai
repository: https://github.com/danielsogl/liquid_ai

environment:
  sdk: ^3.10.8
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_schema: ^5.2.2
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.sogl.liquid_ai
        pluginClass: LiquidAiPlugin
      ios:
        pluginClass: LiquidAiPlugin
